ข้อสอบปลายภาควิชาการประมวลผลข้อมูลขนาดใหญ่
1. จงสร้าง ndarray ดังนี้

In [3]:
import numpy as np

In [4]:
gpas_as_list = np.array([
    [4.   , 3.285, 3.5  , 4.   ],
    [3.2  , 3.8  , 4.   , 4.   ],
    [3.96 , 3.92 , 4.   , 4.   ]
], np.float16)
gpas_as_list

array([[4.   , 3.285, 3.5  , 4.   ],
       [3.2  , 3.8  , 4.   , 4.   ],
       [3.96 , 3.92 , 4.   , 4.   ]], dtype=float16)

2. จงแสดงจำนวน แถว และ คอลัมน์ ของ array ที่สร้างขึ้นจากข้อ 1.

In [5]:
gpas_as_list.shape  

(3, 4)

3. จงสร้าง array ดังต่อไปนี้

'''
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
'''

In [6]:
ten_as_list =[[ 1, 2, 3, 4],
 [ 5, 6, 7, 8],
 [ 9, 10, 11, 12]] 

In [7]:
ten_as_list = np.array(
[[ 1, 2, 3, 4],
 [ 5, 6, 7, 8],
 [ 9, 10, 11, 12]] )
print (ten_as_list)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


4. จากข้อที่ 3 จงแสดงข้อมูลดังต่อไปนี้

'''
[5 6 7 8]
'''

In [8]:
ten_as_list = np.array(
 [ 5, 6, 7, 8])

print (ten_as_list)

[5 6 7 8]


5. จากข้อที่ 3. จงแสดงข้อมูลดังต่อไปนี้

'''
array([12, 11, 10])
'''

In [9]:
x = np.arange(13)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
x[10:]

array([10, 11, 12])

In [11]:
x[::-1]

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [12]:
xs = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
lt = xs[2, 1:]
lt[::-1]

array([12, 11, 10])

6. จงเขียนโปรแกรมที่ทำการเขียนข้อมูลต่อไปนี้ลงในไฟล์ ชื่อ file.txt

'''
This is 1st line
This is 2nd line
This is 3rd line
This is 4th line
This is 5th line
'''

In [13]:
data = ["This is 1st line",
        "This is 2nd line",
        "This is 3rd line",
        "This is 4th line",
        "This is 5th line"]

with open('./file.txt', 'w') as fp:
    for line in data:
        fp.write(line+"\n")
        
with open('./file.txt', 'r') as fp:  
    line = fp.readline()
    while line:
        print("{}".format(line.strip()))
        line = fp.readline()
print("Complete")

This is 1st line
This is 2nd line
This is 3rd line
This is 4th line
This is 5th line
Complete


7. จงเขียนข้อมูลต่อไปนี้ลงในไฟล์ในรูปแบบ CSV

'''
myData = [
            ["first_name", "second_name", "Grade"],
            ['Alex', 'Brian', 'A'],
            ['Tom', 'Smith', 'B']
        ]
'''

In [14]:
import csv
myData = [
            ["first_name", "second_name", "Grade"],
            ['Alex', 'Brian', 'A'],
            ['Tom', 'Smith', 'B']
        ]
with open('./fil.csv', 'w') as myFile:
    writer = csv.writer(myFile)
    writer.writerows(myData)
print("Complete")

Complete


8.จงนำข้อมูลต่อไปนี้ไปสร้างเป็น Data Frame

'''
persons = {
    "ชื่อ": ["พิศาล", "ปรเมษฐ", "สมชาย"],
    "สกุล": ["สุขขี", "สุขะตะ", "รักดี"],
    "โทร": ["0842982456", "0889152456", "0886123546"]
}
'''

In [15]:
import pandas as pd

In [16]:
persons = {
    "ชื่อ": ["พิศาล", "ปรเมษฐ", "สมชาย"],
    "สกุล": ["สุขขี", "สุขะตะ", "รักดี"],
    "โทร": ["0842982456", "0889152456", "0886123546"]
}
data = pd.DataFrame(persons)
data.head()

ชื่อ    สกุล         โทร
0   พิศาล   สุขขี  0842982456
1  ปรเมษฐ  สุขะตะ  0889152456
2   สมชาย   รักดี  0886123546

9. จาก Data Frame ในข้อที่ 8 จงแสดงเฉพาะคอลัม เบอร์โทรศัพท์

In [17]:
data[["โทร"]]

โทร
0  0842982456
1  0889152456
2  0886123546

10. จาก Data Frame ในข้อที่ 8 จงแสดงเฉพาะข้อมูลของ พิศาล

In [18]:
tel = data[data["ชื่อ"]=='พิศาล']

In [19]:
tel

ชื่อ   สกุล         โทร
0  พิศาล  สุขขี  0842982456